language: go

install:
  - make get-deps
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/mattn/goveralls

script:
  - make
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false
